improve re-usability of pipeline job defs
Gitleaks-Sign: djguMzAuMXwyMDI2LTA4LTI0VDE4OjMyOjI3fDYzMmUzMGVjN2ExMzRkNmQ2MDY1YjY3MmJkM2ZiNThlZTdkZjRhZTQ=
Gitleaks-Hash: f2eb72c4964b70ccd35f1e844e2c911829f315934e0816aa8693aaa7c3e13da5

diff --git a/tools/dci-pipeline-helper b/tools/dci-pipeline-helper
--- a/tools/dci-pipeline-helper
+++ b/tools/dci-pipeline-helper
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (C) 2024-2025 Red Hat, Inc.
+# Copyright (C) 2024-2026 Red Hat, Inc.
 #
 # Licensed under the Apache License, Version 2.0 (the "License"); you may
 # not use this file except in compliance with the License. You may obtain
@@ -76,9 +76,9 @@ for arg in "$@"; do
             ;;
         *)
             # Verify if the pipeline file exists
-            pipeline="${PIPELINES_DIR}/${arg}-pipeline.yml"
-            if [ ! -r "$pipeline" ]; then
-                echo "Unable to find $pipeline file" 1>&2
+            pipeline=$(find_pipeline_file "$arg" "$PIPELINES_DIRS")
+            if [ -z "$pipeline" ] || [ ! -r "$pipeline" ]; then
+                echo "Unable to find ${arg}-pipeline.yml file in PIPELINES_DIRS: $PIPELINES_DIRS" 1>&2
                 exit 1
             fi
             names=$(yaml2json "$pipeline"|jq -r '.[].name')
@@ -90,6 +90,12 @@ for arg in "$@"; do
             # copy the pipeline to the temporary directory
             cp $pipeline $TMPDIR || exit 1
             pipeline="$TMPDIR/$(basename $pipeline)"
+
+            # Replace @QUEUE/@RESOURCE
+            sed -i -e "s/@QUEUE/$DCI_QUEUE/g" -e "s/@RESOURCE/$RES/g" "$pipeline"
+
+            # resolve relative inventories after @QUEUE/@RESOURCE replacement
+            resolve_inventories "$pipeline"
 
             if grep -q -E "^\s*-?\s*ansible_playbook\s*:\s*[\"']?/usr/share/dci-openshift-app-agent/dci-openshift-app-agent.yml[\"']?" $pipeline; then
                 CNF_PIPELINES="$CNF_PIPELINES $pipeline"
